import { ISpreadsheet, IBufferManager } from "../types";
import { IGrid } from "../../../ts-grid";
import { EditLine } from "../EditLine";
export declare function isPrintableKey(e: KeyboardEvent): boolean;
export declare function getHtmlData(spreadsheet: ISpreadsheet): string;
export declare function getKeysHandlers(spreadsheet: ISpreadsheet, grid: IGrid, bufferManager: IBufferManager, editLine: EditLine): {
    escape: () => void;
    delete: () => void;
    enter: () => void;
    f2: () => void;
    pageUp: (e: any) => void;
    pageDown: (e: any) => void;
    "ctrl+a": (e: any) => void;
    "shift+arrowLeft": () => void;
    "shift+arrowRight": () => void;
    "shift+arrowDown": () => void;
    "shift+arrowUp": () => void;
    "ctrl+enter": () => void;
    "shift+enter": () => void;
    tab: (e: any) => void;
    "shift+tab": (e: any) => void;
    arrowLeft: (e: any) => void;
    arrowRight: (e: any) => void;
    arrowDown: (e: any) => void;
    arrowUp: (e: any) => void;
    "ctrl+arrowLeft": () => void;
    "ctrl+arrowRight": () => void;
    "ctrl+arrowDown": () => void;
    "ctrl+arrowUp": () => void;
    home: (e: any) => void;
    end: (e: any) => void;
    "ctrl+home": () => void;
    "ctrl+end": () => void;
    "ctrl+z": (e: any) => void;
    "ctrl+y": (e: any) => void;
    "ctrl+shift+z": () => void;
    "ctrl+b": () => void;
    "ctrl+i": () => void;
    "ctrl+u": (e: any) => void;
    backspace: () => void;
};
