import { cellValue } from "../types";
export declare function ISBLANK(val: cellValue): boolean;
export declare function ISBINARY(val: cellValue): boolean;
export declare function ISEVEN(num: cellValue): boolean;
export declare function ISODD(num: cellValue): boolean;
export declare function ISNONTEXT(v: cellValue): boolean;
export declare function ISNUMBER(num: cellValue): boolean;
export declare function ISTEXT(v: cellValue): boolean;
export declare function N(num: cellValue): number;
